research_categories:
  - Addiction
  - Behavioral
  - Economics
  - Education
  - Environmental
  - Ethical
  - Governance
  - Learning
  - Neuro/Cognitive
  - Physiological
  - Policy-making
  - Psychological
  - Sexualization
  - Social
  - Technological
